### ISSUE TITLE
[epic] Release sleepy 0.1.0

### ISSUE THREAD

**Issue by vityaman** [vityaman-edu/sleepy#1]
We should implement sleepy until the end of semester, or better this year.

Plan:
- https://github.com/vityaman-edu/sleepy/issues/2
- [ ] Add initial documentation including useful links, goals.
- https://github.com/vityaman-edu/sleepy/issues/4
- [ ] Write sleepy vm asm specification including code examples.
- [ ] Write sleepy vm specification.
- [ ] Implement sleepy frontend.
  - [ ] Text -> SyntaxTree (`lark`)
    - https://github.com/vityaman-edu/sleepy/issues/5
  - [ ] SyntaxTree -> Program (`st2p`, `sema`)
    - https://github.com/vityaman-edu/sleepy/issues/10
      - [x] Design internal `Program` representation
      - [ ] Design `SymbolSpace`: composable, `Symbol` <-> `Identity`
      - [x] Implement `SyntaxTree` to `Program` converter `st2p`
      - [ ] Design `Program` tools: visitors, listeners and so on.
      - [ ] Implement `source(Program)`
    - [ ] Design `Kind` system
    - [ ] SyntaxTree Analysis (`sema`)
      - [ ] Design `KindInference`: `Identity` -> `Kind`
    - [ ] Implement `dump(Program)`
  - https://github.com/vityaman-edu/sleepy/issues/12
- [ ] Ensure frontend is tested.
- [ ] Implement sleepy vm.
- [ ] Ensure sleepy vm is tested.
- [ ] Write a report
